### PR TITLE
refs #119: check if csrf_token was processed

### LINKED ISSUE #119: csrf_token error on  django 1.8
If use template tag {% csrf_token %} and `django.middleware.csrf.CsrfViewMiddleware` is not in MIDDLEWARE_CLASSES error raised:

```
Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py" in inner
  145.                     return func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "./elec/contrib/users/decorators.py" in _wrapped_view
  22.         return view_func(request, *args, **kwargs)
File "./elec/contrib/catalog/views/controlpanel.py" in company_order_create
  95.         'order_form': order_form,
File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py" in render
  67.             template_name, context, request=request, using=using)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py" in render_to_string
  99.         return template.render(context, request)
File "/usr/local/lib/python2.7/dist-packages/django_jinja/backend.py" in render
  51.         return self.template.render(context)
File "/usr/lib/python2.7/dist-packages/jinja2/environment.py" in render
  969.         return self.environment.handle_exception(exc_info, True)
File "/usr/lib/python2.7/dist-packages/jinja2/environment.py" in handle_exception
  742.         reraise(exc_type, exc_value, tb)
File "./elec/contrib/catalog/templates/catalog/controlpanel/company_create.jinja" in top-level template code
  2. {% from "catalog/controlpanel/macro.jinja" import controlpanel_menu %}
File "./elec/contrib/users/templates/users/base.jinja" in top-level template code
  1. {% extends "layouts/base.jinja" %}
File "./elec/common/templates/layouts/base.jinja" in top-level template code
  228. {%- block content %}{% endblock %}
File "./elec/contrib/users/templates/users/base.jinja" in block "content"
  11.     {% block content_inner %}{% endblock %}
File "./elec/contrib/catalog/templates/catalog/controlpanel/company_create.jinja" in block "content_inner"
  11. <form enctype="multipart/form-data" action="{{ request.get_full_path() }}" method="post">
File "/usr/local/lib/python2.7/dist-packages/django_jinja/builtins/extensions.py" in _render
  68.         if csrf_token:
File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py" in __wrapper__
  137.                 return getattr(res, method_name)(*args, **kw)

Exception Type: AttributeError at /users/company/create
Exception Value: 'NoneType' object has no attribute '__len__'
```

### PR DESCRIPTION
**Pull request by kazmiruk**
Should fix #119 bug

### CODE REVIEW

**Comment by niwibe** [comment]
But this requires that request will be available in the template, context? I'm right?

**Comment by kazmiruk** [comment]
Yes, you are

**Comment by niwibe** [comment]
This seems really a bad bad approach, templates should not receive request... is a very bad practice access to request from templates in my opionon. 

Lamentably I can not accept this PR, sorry. In any case, thanks for your efforts.

**Comment by kazmiruk** [comment]
It ok :) I'd like to use original version of lib, not my fork. And this is an approach that I use to avoid and exception. I'll wait fix
